spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_market?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
    username: "root"
    password: "root"
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: SELECT 1
        max-active: 10
        initial-size: 1
        max-wait: 60000
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.market.market_user.entity
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
